---
kind: pipeline
type: docker
name: testing

trigger:
  event: [push]
  branch:
    exclude: [build]

steps:
  - name: yarn-install
    image: node:22
    when:
      event: [push]
    commands:
      - yarn
  
  - name: lint-frontend
    image: node:22
    depends_on:
      - yarn-install
    commands:
      - yarn lint

  - name: typescript
    image: node:22
    depends_on:
      - yarn-install
    commands:
      - yarn types

  - name: build-frontend
    image: node:22
    depends_on:
      - yarn-install
    environment:
      LANG: C.UTF-8
    commands:
      - yarn build
  
  - name: check-unused
    image: node:22
    depends_on:
      - yarn-install
    commands:
      - yarn knip
  
  - name: missing-migrations
    image: abakus/lego-testbase:python3.12poetry1.8.5
    environment:
      DATABASE: database
    commands:
      - make ci_settings
      - tox -e missing-migrations
  
  - name: tests
    image: abakus/lego-testbase:python3.12poetry1.8.5
    environment:
      DATABASE: database
    commands:
      - tox -e tests

  - name: coverage
    image: abakus/lego-testbase:python3.12poetry1.8.5
    depends_on:
      - tests
    environment:
      DATABASE: database
    commands:
      - tox -e coverage

  - name: isort
    image: abakus/lego-testbase:python3.12poetry1.8.5
    commands:
      - tox -e isort
  
  - name: black
    image: abakus/lego-testbase:python3.12poetry1.8.5
    commands:
      - tox -e black
  
  - name: cypress-install
    image: node:22
    depends_on:
      - lint-frontend
      - typescript
      - build-frontend
      - check-unused
      - missing-migrations
      - coverage
      - isort
      - black
    environment:
      CYPRESS_CACHE_FOLDER: /drone/src/.cypress_cache
    commands:
      - yarn cypress install

  - name: cypress-backend
    image: abakus/lego-testbase:python3.12poetry1.8.5
    detach: true
    when:
      event: [push]
    depends_on:
      - build-frontend
    environment:
      LANG: C.UTF-8
      DATABASE: database
      FRONTEND_URL: "https://localhost:5000"
      API_URL: "/api"
    commands:
    - make ci_settings
    - poetry install
    - poetry run python manage.py collectstatic --noinput
    - poetry run python manage.py migrate
    - poetry run python manage.py load_fixtures
    - poetry run python manage.py runserver 0.0.0.0:5000

  - name: cypress
    image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
    when:
      event: [push]
    depends_on:
      - cypress-install
    environment:
      CYPRESS_BASE_URL: http://cypress-backend:5000
      CYPRESS_CACHE_FOLDER: /drone/src/.cypress_cache
      CYPRESS_RECORD_KEY:
        from_secret: cypress_record_key
    commands:
      - ./wait-for-it.sh -t 420 cypress-backend:5000
      - yarn cypress:run --record

services:
  - name: database
    image: postgres:14.4
    environment:
      POSTGRES_USER: admissions
      POSTGRES_HOST_AUTH_METHOD: trust

---
kind: pipeline
type: docker
name: deployment

trigger:
  event: [push]
  branch: [build]

steps:
  - name: docker
    image: plugins/docker
    when:
      branch:
        - build
      status: [success]
      event: [push]
    settings:
      registry: https://registry.webkom.dev
      repo: registry.webkom.dev/webkom/admissions
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - version-${DRONE_COMMIT_SHA:0:7}
      build_args:
        - "RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}"

  - name: Deploy
    image: abakus/ansible-deploy
    settings:
      playbook: /infrastructure/esas/playbooks/deploy.yml
      repository:
        from_secret: infra_repository
      tags:
        - admissions
      # limit: esas
      limit: ${DRONE_DEPLOY_TO}
      extra_vars: admissions_version=version-${DRONE_COMMIT_SHA:0:7}
      inventory: /infrastructure/inventory
      vault_password:
        from_secret: ansible_vault_password
      private_key:
        from_secret: infra_deploy_key
    when:
      event:
        - promote
        - rollback
      branch:
        - build
      status: [success]
