[tool.poetry]
name = "admissions"
version = "0.1.0"
description = "Admission system for Abakus"
authors = ["Webkom <webkom@abakus.no>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.1.6"
django-environ = "^0.9.0"
django-extensions = "^3.2.1"
djangorestframework = "^3.14.0"
django-cors-headers = "^3.13.0"
django-vite = "^2.0.2"
social-auth-app-django = "^5.0.0"
psycopg2-binary = "^2.9.5"
ipython = "^8.10.0"
structlog = "^22.3.0"
sentry-sdk = "^1.15.0"
uwsgi = "^2.0.21"


[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^3.8.1"
factory-boy = "^2.12.0"
tox = "^4.4.6"
isort = "^5.12.0"
black = "^23.1.0"
coverage = "^7.0.3"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.5.1"]
build-backend = "poetry.core.masonry.api"
