# Generated by Django 2.0.3 on 2018-03-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admissions", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        )
    ]
