# Generated by Django 4.0.6 on 2022-08-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0002_alter_legouser_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
