# Generated by Django 2.0.3 on 2018-08-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_committee_detail_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapplication',
            old_name='priority_text',
            new_name='text',
        ),
    ]
