# Generated by Django 2.0.3 on 2018-08-10 19:53

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('admissions', '0008_auto_20180805_0926'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='abakus_group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.CreateModel(
            name='LegoUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.LegoUser'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
