# Generated by Django 2.0.3 on 2018-08-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("admissions", "0011_auto_20180822_1847")]

    operations = [migrations.RemoveField(model_name="membership", name="abakus_group")]
