# Generated by Django 2.0.3 on 2018-08-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admissions", "0013_userapplication_phone_number")]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="description",
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="committee",
            name="response_label",
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
