# Generated by Django 2.2.4 on 2019-08-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("admissions", "0014_auto_20180824_1710")]

    operations = [
        migrations.RemoveField(model_name="userapplication", name="time_sent")
    ]
