# Generated by Django 5.1.5 on 2025-03-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique_user_group_combination",
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "group", "role"), name="unique_user_group_role"
            ),
        ),
    ]
