# Generated by Django 5.1.5 on 2025-04-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0002_remove_membership_unique_user_group_combination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name="group",
            name="response_label",
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
