# Generated by Django 5.1.5 on 2026-04-23 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_alter_group_description_alter_group_response_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule", models.JSONField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("session_duration", models.PositiveIntegerField(default=60)),
                ("enabled_slots", models.JSONField(blank=True, default=list)),
                ("day_start_minute", models.PositiveIntegerField(default=480)),
                ("day_end_minute", models.PositiveIntegerField(default=1080)),
                ("chunk_size", models.PositiveIntegerField(default=4)),
                ("chunk_break_minutes", models.PositiveIntegerField(default=0)),
                ("is_distributed", models.BooleanField(default=False)),
                ("show_candidate_names", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_schedule",
                        to="admissions.admission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slots", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_availabilities",
                        to="admissions.admission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_availabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("admission", "user"),
                        name="unique_admission_user_availability",
                    )
                ],
            },
        ),
    ]
