# Generated by Django 4.0.6 on 2022-08-07 23:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0003_alter_committee_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_applications",
                        to="admissions.userapplication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="committee",
            new_name="group",
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("user", "group")},
        ),
        migrations.RenameModel(
            old_name="Committee",
            new_name="Group",
        ),
        migrations.DeleteModel(
            name="CommitteeApplication",
        ),
        migrations.AddField(
            model_name="groupapplication",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="admissions.group",
            ),
        ),
    ]
