# Generated by Django 5.2.16 on 2026-07-26 21:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def assert_no_duplicate_group_applications(apps, schema_editor):
    """Refuse to guess which real applicant record should survive."""
    GroupApplication = apps.get_model("admissions", "GroupApplication")
    database = schema_editor.connection.alias
    duplicates = list(
        GroupApplication.objects.using(database)
        .values("application_id", "group_id")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
        .order_by("application_id", "group_id")[:20]
    )
    if duplicates:
        sample = ", ".join(
            (
                f"application={row['application_id']} "
                f"group={row['group_id']} rows={row['row_count']}"
            )
            for row in duplicates
        )
        raise RuntimeError(
            "Duplicate committee applications must be reviewed and resolved "
            "before applying 0004_scheduler_domain. No rows were deleted. "
            f"First conflicts: {sample}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_alter_group_description_alter_group_response_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slots", models.JSONField(blank=True, default=list)),
                ("conflicts", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SavedSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedule", models.JSONField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("session_duration", models.PositiveIntegerField(default=60)),
                ("enabled_windows", models.JSONField(blank=True, default=list)),
                ("enabled_slots", models.JSONField(blank=True, default=list)),
                ("day_start_minute", models.PositiveIntegerField(default=480)),
                ("day_end_minute", models.PositiveIntegerField(default=1080)),
                ("chunk_size", models.PositiveIntegerField(default=4)),
                ("chunk_break_minutes", models.PositiveIntegerField(default=0)),
                ("panel_size", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("solver_options", models.JSONField(blank=True, null=True)),
                ("is_distributed", models.BooleanField(default=False)),
                (
                    "name_visibility",
                    models.CharField(
                        choices=[
                            ("hidden", "Hidden"),
                            ("admin_only", "Admin only"),
                            ("committee", "Committee"),
                        ],
                        default="hidden",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SolveJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("DONE", "Done"),
                            ("ERROR", "Error"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("request_data", models.JSONField()),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="legouser",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="admission",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            assert_no_duplicate_group_applications,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="groupapplication",
            constraint=models.UniqueConstraint(
                fields=("application", "group"),
                name="unique_application_group_combination",
            ),
        ),
        migrations.AddField(
            model_name="interviewavailability",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_availabilities",
                to="admissions.admission",
            ),
        ),
        migrations.AddField(
            model_name="interviewavailability",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_availabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedschedule",
            name="admission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_schedule",
                to="admissions.admission",
            ),
        ),
        migrations.AddField(
            model_name="solvejob",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solve_jobs",
                to="admissions.admission",
            ),
        ),
        migrations.AddField(
            model_name="solvejob",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewavailability",
            constraint=models.UniqueConstraint(
                fields=("admission", "user"), name="unique_admission_user_availability"
            ),
        ),
    ]
