# Generated by Django 4.0.7 on 2022-09-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admissions",
            "0004_groupapplication_rename_committee_membership_group_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="admissions",
            field=models.ManyToManyField(to="admissions.admission"),
        ),
    ]
