# Generated by Django 5.2.16 on 2026-07-26 21:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0004_scheduler_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameVisibilityAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_name", models.CharField(max_length=80)),
                ("actor_username", models.CharField(max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[("revealed", "Revealed"), ("hidden", "Hidden")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="savedschedule",
            name="revealed_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="revealed_interview_schedules",
                to="admissions.group",
            ),
        ),
        migrations.AddIndex(
            model_name="solvejob",
            index=models.Index(
                fields=["status", "created_at"], name="admissions__status_c65d93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solvejob",
            index=models.Index(
                fields=["admission", "status"], name="admissions__admissi_980e4a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="solvejob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("PENDING", "RUNNING"))),
                fields=("admission",),
                name="unique_active_solve_job_per_admission",
            ),
        ),
        migrations.AddField(
            model_name="namevisibilityauditevent",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="name_visibility_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="namevisibilityauditevent",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="name_visibility_events",
                to="admissions.admission",
            ),
        ),
        migrations.AddField(
            model_name="namevisibilityauditevent",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admissions.group",
            ),
        ),
        migrations.AddField(
            model_name="namevisibilityauditevent",
            name="saved_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="name_visibility_events",
                to="admissions.savedschedule",
            ),
        ),
        migrations.AddIndex(
            model_name="namevisibilityauditevent",
            index=models.Index(
                fields=["admission", "-created_at"], name="name_vis_admission_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="namevisibilityauditevent",
            index=models.Index(
                fields=["group", "-created_at"], name="name_vis_group_time_idx"
            ),
        ),
    ]
