# Generated by Django 5.2.16 on 2026-07-27 06:34

import uuid
from datetime import timedelta

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def normalize_admission_dates(apps, schema_editor):
    Admission = apps.get_model("admissions", "Admission")
    database = schema_editor.connection.alias
    Admission.objects.using(database).filter(
        public_deadline__lte=F("open_from")
    ).update(open_from=F("public_deadline") - timedelta(minutes=1))
    Admission.objects.using(database).filter(
        closed_from__lt=F("public_deadline")
    ).update(closed_from=F("public_deadline"))


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0005_scheduler_authority"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConflictReviewAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_username", models.CharField(max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("closed", "Closed"),
                            ("viewed", "Viewed"),
                            ("submitted", "Submitted"),
                            ("frozen", "Frozen"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reviewed_candidate_ids", models.JSONField(blank=True, default=list)),
                ("conflict_candidate_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewStatusAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_username", models.CharField(max_length=150)),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("not_invited", "Not invited"),
                            ("invited", "Invited"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("not_invited", "Not invited"),
                            ("invited", "Invited"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="admissiongroup",
            name="header_fields",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name="groupapplication",
            name="header_fields_response",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name="interviewavailability",
            name="reviewed_candidate_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="savedschedule",
            name="conflict_review_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="interview_status",
            field=models.CharField(
                choices=[
                    ("not_invited", "Not invited"),
                    ("invited", "Invited"),
                    ("confirmed", "Confirmed"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_invited",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="interview_status_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="interview_status_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interview_status_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="interview_status_updated_by_username",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.RunPython(
            normalize_admission_dates,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="admission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_deadline__gt", models.F("open_from")),
                    ("closed_from__gte", models.F("public_deadline")),
                ),
                name="admission_dates_in_chronological_order",
            ),
        ),
        migrations.AddField(
            model_name="conflictreviewauditevent",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conflict_review_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conflictreviewauditevent",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflict_review_events",
                to="admissions.admission",
            ),
        ),
        migrations.AddField(
            model_name="conflictreviewauditevent",
            name="saved_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conflict_review_events",
                to="admissions.savedschedule",
            ),
        ),
        migrations.AddField(
            model_name="interviewstatusauditevent",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interview_status_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interviewstatusauditevent",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_status_events",
                to="admissions.userapplication",
            ),
        ),
        migrations.AddIndex(
            model_name="conflictreviewauditevent",
            index=models.Index(
                fields=["admission", "-created_at"], name="conflict_review_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewstatusauditevent",
            index=models.Index(
                fields=["application", "-created_at"],
                name="interview_status_app_time_idx",
            ),
        ),
    ]
