# Generated by Django 5.2.16 on 2026-07-27 06:34

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError
from django.db.models import F, Q


def backfill_group_scoped_application_answers(apps, schema_editor):
    Admission = apps.get_model("admissions", "Admission")
    AdmissionGroup = apps.get_model("admissions", "AdmissionGroup")
    UserApplication = apps.get_model("admissions", "UserApplication")
    GroupApplication = apps.get_model("admissions", "GroupApplication")
    database = schema_editor.connection.alias

    for admission in Admission.objects.using(database).iterator():
        legacy_fields = admission.header_fields
        if not legacy_fields:
            continue
        for admission_group in AdmissionGroup.objects.using(database).filter(
            admission_id=admission.pk
        ):
            if admission_group.header_fields:
                continue
            AdmissionGroup.objects.using(database).filter(
                pk=admission_group.pk,
                header_fields=[],
            ).update(header_fields=legacy_fields)

    for application in UserApplication.objects.using(database).iterator():
        legacy_answers = application.header_fields_response
        if not legacy_answers:
            continue
        for group_application in GroupApplication.objects.using(database).filter(
            application_id=application.pk
        ):
            if group_application.header_fields_response:
                continue
            GroupApplication.objects.using(database).filter(
                pk=group_application.pk,
                header_fields_response={},
            ).update(header_fields_response=legacy_answers)


def restore_legacy_application_answers(apps, schema_editor):
    Admission = apps.get_model("admissions", "Admission")
    AdmissionGroup = apps.get_model("admissions", "AdmissionGroup")
    UserApplication = apps.get_model("admissions", "UserApplication")
    GroupApplication = apps.get_model("admissions", "GroupApplication")
    database = schema_editor.connection.alias
    admission_updates = []
    application_updates = []

    for admission in Admission.objects.using(database).iterator():
        scoped_values = list(
            AdmissionGroup.objects.using(database)
            .filter(admission_id=admission.pk)
            .order_by("pk")
            .values_list("header_fields", flat=True)
        )
        if not scoped_values:
            continue
        first_value = scoped_values[0]
        if any(value != first_value for value in scoped_values[1:]):
            raise IrreversibleError(
                "Committee question sets have diverged and cannot be represented "
                "by the legacy admission field."
            )
        admission_updates.append((admission.pk, first_value))

    for application in UserApplication.objects.using(database).iterator():
        scoped_values = list(
            GroupApplication.objects.using(database)
            .filter(application_id=application.pk)
            .order_by("pk")
            .values_list("header_fields_response", flat=True)
        )
        if not scoped_values:
            continue
        first_value = scoped_values[0]
        if any(value != first_value for value in scoped_values[1:]):
            raise IrreversibleError(
                "Committee answers have diverged and cannot be represented by "
                "the legacy application field."
            )
        application_updates.append((application.pk, first_value))

    for admission_id, fields in admission_updates:
        Admission.objects.using(database).filter(pk=admission_id).update(
            header_fields=fields
        )
    for application_id, answers in application_updates:
        UserApplication.objects.using(database).filter(pk=application_id).update(
            header_fields_response=answers
        )


def assert_admission_dates_are_chronological(apps, schema_editor):
    Admission = apps.get_model("admissions", "Admission")
    database = schema_editor.connection.alias
    invalid = list(
        Admission.objects.using(database)
        .filter(
            Q(public_deadline__lte=F("open_from"))
            | Q(closed_from__lt=F("public_deadline"))
        )
        .order_by("pk")
        .values("pk", "slug", "open_from", "public_deadline", "closed_from")[:20]
    )
    if invalid:
        sample = ", ".join(
            (
                f"id={row['pk']} slug={row['slug']} "
                f"open={row['open_from'].isoformat()} "
                f"deadline={row['public_deadline'].isoformat()} "
                f"closed={row['closed_from'].isoformat()}"
            )
            for row in invalid
        )
        raise RuntimeError(
            "Admission dates must be reviewed and corrected before applying "
            "0006_scheduler_workflow. No historical dates were rewritten. "
            f"First conflicts: {sample}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0005_scheduler_authority"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConflictReviewAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_username", models.CharField(max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("closed", "Closed"),
                            ("viewed", "Viewed"),
                            ("submitted", "Submitted"),
                            ("frozen", "Frozen"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reviewed_candidate_ids", models.JSONField(blank=True, default=list)),
                ("conflict_candidate_ids", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewStatusAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_username", models.CharField(max_length=150)),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("not_invited", "Not invited"),
                            ("invited", "Invited"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("not_invited", "Not invited"),
                            ("invited", "Invited"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="admissiongroup",
            name="header_fields",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name="groupapplication",
            name="header_fields_response",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.RunPython(
            backfill_group_scoped_application_answers,
            restore_legacy_application_answers,
        ),
        migrations.AddField(
            model_name="interviewavailability",
            name="reviewed_candidate_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="savedschedule",
            name="conflict_review_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="interview_status",
            field=models.CharField(
                choices=[
                    ("not_invited", "Not invited"),
                    ("invited", "Invited"),
                    ("confirmed", "Confirmed"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_invited",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="interview_status_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="interview_status_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interview_status_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="interview_status_updated_by_username",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.RunPython(
            assert_admission_dates_are_chronological,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="admission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("public_deadline__gt", models.F("open_from")),
                    ("closed_from__gte", models.F("public_deadline")),
                ),
                name="admission_dates_in_chronological_order",
            ),
        ),
        migrations.AddField(
            model_name="conflictreviewauditevent",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conflict_review_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conflictreviewauditevent",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflict_review_events",
                to="admissions.admission",
            ),
        ),
        migrations.AddField(
            model_name="conflictreviewauditevent",
            name="saved_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conflict_review_events",
                to="admissions.savedschedule",
            ),
        ),
        migrations.AddField(
            model_name="interviewstatusauditevent",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interview_status_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interviewstatusauditevent",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_status_events",
                to="admissions.userapplication",
            ),
        ),
        migrations.AddIndex(
            model_name="conflictreviewauditevent",
            index=models.Index(
                fields=["admission", "-created_at"], name="conflict_review_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interviewstatusauditevent",
            index=models.Index(
                fields=["application", "-created_at"],
                name="interview_status_app_time_idx",
            ),
        ),
    ]
