# Generated by Django 4.0.7 on 2022-12-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0005_group_admissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
