# Generated by Django 5.2.16 on 2026-07-27 07:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0006_scheduler_workflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleDeviationApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_username", models.CharField(max_length=150)),
                ("schedule_fingerprint", models.CharField(max_length=64)),
                ("deviation_fingerprint", models.CharField(max_length=64)),
                ("policy_snapshot", models.JSONField(default=dict)),
                ("availability_generation", models.PositiveIntegerField()),
                ("layout_version", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="interviewavailability",
            name="participation",
            field=models.CharField(
                choices=[
                    ("awaiting_response", "Awaiting response"),
                    ("participating", "Participating"),
                    ("not_participating", "Not participating"),
                ],
                default="awaiting_response",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="interviewavailability",
            name="submitted_grid_generation",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedschedule",
            name="availability_generation",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="savedschedule",
            name="block_mode",
            field=models.CharField(
                choices=[("standard", "Standard blocks"), ("manual", "Manual blocks")],
                default="standard",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="savedschedule",
            name="layout_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="savedschedule",
            name="resolved_blocks",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="savedschedule",
            name="slot_overrides",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="solvejob",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solvejob",
            name="discarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solvejob",
            name="request_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="solvejob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("applied_at__isnull", True),
                    ("discarded_at__isnull", True),
                    _connector="OR",
                ),
                name="solve_job_not_applied_and_discarded",
            ),
        ),
        migrations.AddField(
            model_name="scheduledeviationapproval",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule_deviation_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scheduledeviationapproval",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_deviation_approvals",
                to="admissions.admission",
            ),
        ),
        migrations.AddField(
            model_name="scheduledeviationapproval",
            name="saved_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deviation_approvals",
                to="admissions.savedschedule",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledeviationapproval",
            index=models.Index(
                fields=["saved_schedule", "deviation_fingerprint"],
                name="sched_dev_fingerprint_idx",
            ),
        ),
    ]
