# Generated by Django 4.1.7 on 2023-04-09 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0006_admission_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="admission",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="admission",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
