# Generated by Django 4.2 on 2023-04-27 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admissions",
            "0007_admission_created_by_alter_admission_description_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="admission",
            old_name="application_deadline",
            new_name="closed_from",
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="userapplication",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="group",
            name="admissions",
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "group"), name="unique_user_group_combination"
            ),
        ),
        migrations.AddConstraint(
            model_name="userapplication",
            constraint=models.UniqueConstraint(
                fields=("admission", "user"), name="unique_admission_user_combination"
            ),
        ),
        migrations.AddField(
            model_name="admissiongroup",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admissions.admission"
            ),
        ),
        migrations.AddField(
            model_name="admissiongroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admissions.group"
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="groups",
            field=models.ManyToManyField(
                through="admissions.AdmissionGroup", to="admissions.group"
            ),
        ),
        migrations.AddConstraint(
            model_name="admissiongroup",
            constraint=models.UniqueConstraint(
                fields=("admission", "group"), name="unique_admission_group_combination"
            ),
        ),
    ]
