# Generated by Django 5.1.5 on 2026-06-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0007_savedschedule_name_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedschedule",
            name="panel_size",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedschedule",
            name="solver_options",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
