# Generated by Django 4.2 on 2023-04-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0008_admissiongroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="slug",
            field=models.SlugField(default="", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
