# Generated by Django 5.1.5 on 2026-06-20 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def dedupe_group_applications(apps, schema_editor):
    """Drop any duplicate (application, group) rows before the unique constraint.

    The write path has always used update_or_create on (application, group), so
    duplicates should not exist, but a stray pair would make AddConstraint fail.
    Keep the most recently updated row in each group and delete the rest.
    """
    GroupApplication = apps.get_model("admissions", "GroupApplication")
    seen = set()
    duplicate_ids = []
    for row in GroupApplication.objects.order_by(
        "application_id", "group_id", "-updated_at"
    ).values("id", "application_id", "group_id"):
        key = (row["application_id"], row["group_id"])
        if key in seen:
            duplicate_ids.append(row["id"])
        else:
            seen.add(key)
    if duplicate_ids:
        GroupApplication.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0009_normalize_slot_keys_and_candidate_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(dedupe_group_applications, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="groupapplication",
            constraint=models.UniqueConstraint(
                fields=("application", "group"),
                name="unique_application_group_combination",
            ),
        ),
    ]
