# Generated by Django 5.1.5 on 2026-06-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0010_alter_admission_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="legouser",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
