# Generated by Django 4.2.1 on 2024-01-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0010_admission_admin_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="header_fields",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="header_fields_response",
            field=models.JSONField(default=None, null=True),
        ),
    ]
