# Generated by Django 4.2.1 on 2023-07-07 18:13

import admissions.admissions.fields.jsonschemaquestionfield
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0010_admission_admin_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupapplication",
            name="text",
        ),
        migrations.RemoveField(
            model_name="userapplication",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="userapplication",
            name="text",
        ),
        migrations.AddField(
            model_name="admission",
            name="questions",
            field=admissions.admissions.fields.jsonschemaquestionfield.JSONSchemaQuestionField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="admissiongroup",
            name="questions",
            field=admissions.admissions.fields.jsonschemaquestionfield.JSONSchemaQuestionField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="groupapplication",
            name="responses",
            field=admissions.admissions.fields.jsonschemaquestionfield.JSONSchemaQuestionField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="responses",
            field=admissions.admissions.fields.jsonschemaquestionfield.JSONSchemaQuestionField(
                blank=True, default=dict
            ),
        ),
    ]
