# Generated by Django 4.2.3 on 2023-07-24 05:00

import admissions.admissions.fields.jsonschemaquestionfield
import admissions.admissions.fields.jsonschemaresponsefield
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0010_admission_admin_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="response_label",
        ),
        migrations.RemoveField(
            model_name="groupapplication",
            name="text",
        ),
        migrations.RemoveField(
            model_name="userapplication",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="userapplication",
            name="text",
        ),
        migrations.AddField(
            model_name="admission",
            name="questions",
            field=admissions.admissions.fields.jsonschemaquestionfield.JSONSchemaQuestionField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="questions",
            field=admissions.admissions.fields.jsonschemaquestionfield.JSONSchemaQuestionField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="groupapplication",
            name="responses",
            field=admissions.admissions.fields.jsonschemaresponsefield.JSONSchemaResponseField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="responses",
            field=admissions.admissions.fields.jsonschemaresponsefield.JSONSchemaResponseField(
                blank=True, default=dict
            ),
        ),
    ]
