# Generated by Django 5.1.5 on 2026-06-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0013_alter_solvejob_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="solvejob",
            index=models.Index(
                fields=["status", "created_at"], name="admissions__status_c65d93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solvejob",
            index=models.Index(
                fields=["admission", "status"], name="admissions__admissi_980e4a_idx"
            ),
        ),
    ]
