# Generated by Django 5.1.5 on 2026-07-03 17:26

from django.db import migrations, models
from django.db.models import Count
from django.utils import timezone


def deduplicate_active_jobs(apps, schema_editor):
    SolveJob = apps.get_model("admissions", "SolveJob")
    duplicates = (
        SolveJob.objects.filter(status__in=("PENDING", "RUNNING"))
        .values("admission_id")
        .annotate(job_count=Count("id"))
        .filter(job_count__gt=1)
    )
    for duplicate in duplicates.iterator():
        jobs = SolveJob.objects.filter(
            admission_id=duplicate["admission_id"],
            status__in=("PENDING", "RUNNING"),
        ).order_by("created_at", "id")
        keep_id = jobs.values_list("id", flat=True).first()
        jobs.exclude(id=keep_id).update(
            status="ERROR",
            error="Erstattet av en annen aktiv solverjobb under oppgradering.",
            finished_at=timezone.now(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0014_solvejob_admissions__status_c65d93_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(deduplicate_active_jobs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="solvejob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("PENDING", "RUNNING"))),
                fields=("admission",),
                name="unique_active_solve_job_per_admission",
            ),
        ),
    ]
