# Generated by Django 5.2.16 on 2026-07-13 13:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_savedschedule_revealed_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameVisibilityAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_name", models.CharField(max_length=80)),
                ("actor_username", models.CharField(max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[("revealed", "Revealed"), ("hidden", "Hidden")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="name_visibility_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name_visibility_events",
                        to="admissions.admission",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admissions.group",
                    ),
                ),
                (
                    "saved_schedule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="name_visibility_events",
                        to="admissions.savedschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["admission", "-created_at"],
                        name="name_vis_admission_time_idx",
                    ),
                    models.Index(
                        fields=["group", "-created_at"], name="name_vis_group_time_idx"
                    ),
                ],
            },
        ),
    ]
