# Generated by Django 5.2.16 on 2026-08-18 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0033_admission_group_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewavailability",
            name="fadderbarn_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FadderbarnDeclaration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lego_user_id", models.IntegerField()),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                ("full_name", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fadderbarn_declarations",
                        to="admissions.admission",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fadderbarn_declarations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["admission", "lego_user_id"],
                        name="admissions__admissi_df2f34_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("admission", "interviewer", "lego_user_id"),
                        name="unique_fadderbarn_per_interviewer",
                    )
                ],
            },
        ),
    ]
