# Generated by Django 5.2.16 on 2026-08-18 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0034_fadderbarn_declarations"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConflictReviewList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.UUIDField()),
                ("own_candidate_ids", models.JSONField(blank=True, default=list)),
                ("swap_candidate_ids", models.JSONField(blank=True, default=list)),
                ("decoys", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_review_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saved_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_review_lists",
                        to="admissions.savedschedule",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("saved_schedule", "interviewer", "revision"),
                        name="unique_conflict_review_list_per_revision",
                    )
                ],
            },
        ),
    ]
