# Generated by Django 5.2.16 on 2026-08-20 10:06

import datetime

from django.db import migrations, models


def backfill_distributed_through(apps, schema_editor):
    # is_distributed is still a real, writable boolean column at this point
    # in the migration - the next operation is what turns it into a
    # generated one. Every already-published plan gets a boundary past its
    # own end_date, so nothing that was visible before this migration
    # becomes invisible because of it.
    SavedSchedule = apps.get_model("admissions", "SavedSchedule")
    for saved in SavedSchedule.objects.filter(is_distributed=True):
        boundary = saved.end_date or saved.start_date
        if boundary is not None:
            boundary = boundary + datetime.timedelta(days=1)
        else:
            boundary = datetime.date.today()
        saved.distributed_through = boundary
        saved.save(update_fields=["distributed_through"])


def reverse_backfill(apps, schema_editor):
    # No-op: reversing AddField drops the column anyway, and is_distributed
    # goes back to being a plain boolean at that point.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0039_directory_entry_and_decoy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedschedule',
            name='distributed_through',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_distributed_through, reverse_backfill),
        # Postgres/Django don't support converting a plain column into a
        # generated one via ALTER - the field has to be dropped and re-added.
        migrations.RemoveField(
            model_name='savedschedule',
            name='is_distributed',
        ),
        migrations.AddField(
            model_name='savedschedule',
            name='is_distributed',
            field=models.GeneratedField(db_persist=True, expression=models.ExpressionWrapper(models.Q(('distributed_through__isnull', False)), output_field=models.BooleanField()), output_field=models.BooleanField()),
        ),
    ]
