# Generated by Django 5.2.16 on 2026-08-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0042_committee_scoped_scheduling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedschedule',
            name='revealed_groups',
        ),
    ]
