# Generated by Django 5.2.17 on 2026-08-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0043_remove_savedschedule_revealed_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewavailability",
            name="discouraged_slots",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
