# Generated by Django 5.2.17 on 2026-08-24 20:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0045_alter_membership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeRosterEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "member"),
                            ("leader", "leader"),
                            ("co-leader", "co-leader"),
                            ("treasurer", "treasurer"),
                            ("recruiting", "recruiting"),
                            ("development", "development"),
                            ("editor", "editor"),
                            ("retiree", "retiree"),
                            ("media_relations", "media_relations"),
                            ("active_retiree", "active_retiree"),
                            ("alumni", "alumni"),
                            ("webmaster", "webmaster"),
                            ("interest_group_admin", "interest_group_admin"),
                            ("alumni_admin", "alumni_admin"),
                            ("retiree_email", "retiree_email"),
                            ("company_admin", "company_admin"),
                            ("dugnad_admin", "dugnad_admin"),
                            ("trip_admin", "trip_admin"),
                            ("sponsor_admin", "sponsor_admin"),
                            ("social_admin", "social_admin"),
                            ("merch_admin", "merch_admin"),
                            ("hs_representative", "hs_representative"),
                            ("cuddling_manager", "cuddling_manager"),
                            ("photo_admin", "photo_admin"),
                            ("graphic_admin", "graphic_admin"),
                            ("social_media_admin", "social_media_admin"),
                            ("booking_admin", "booking_admin"),
                            ("purchasing_manager", "purchasing_manager"),
                            ("event_manager", "event_manager"),
                            ("snackoverflow_manager", "snackoverflow_manager"),
                        ],
                        default="member",
                        max_length=30,
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_entries",
                        to="admissions.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "user"), name="unique_roster_group_user"
                    )
                ],
            },
        ),
    ]
