# Generated by Django 5.2.17 on 2026-08-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0047_goduser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goduser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
