# Generated by Django 5.2.17 on 2026-08-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0048_alter_goduser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedschedule",
            name="outreach_templates",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
