# Generated by Django 5.2.17 on 2026-08-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0049_savedschedule_outreach_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedschedule",
            name="published_without_review_by",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="conflictreviewauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("opened", "Opened"),
                    ("closed", "Closed"),
                    ("viewed", "Viewed"),
                    ("submitted", "Submitted"),
                    ("frozen", "Frozen"),
                    ("bypassed", "Bypassed"),
                ],
                max_length=16,
            ),
        ),
    ]
