# Generated by Django 5.2.17 on 2026-08-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0051_interview_status_per_committee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupapplication",
            options={"ordering": ["created_at"]},
        ),
    ]
