# Generated by Django 5.2.17 on 2026-08-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0053_solvejob_preview_result_solvejob_preview_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="conflictreviewlist",
            name="pool_candidate_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
