# Generated by Django 5.2.17 on 2026-08-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0054_conflictreviewlist_pool_candidate_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedschedule",
            name="completed_days",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
