# Generated by Django 5.2.17 on 2026-09-02 01:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0056_savedschedule_published_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_name", models.CharField(max_length=80)),
                (
                    "candidate_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "candidate_full_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "candidate_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("full", "Full withdrawal"),
                            ("partial", "Single committee"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdrawal_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_events",
                        to="admissions.admission",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admissions.group",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["admission", "-created_at"],
                        name="withdrawal_adm_time_idx",
                    ),
                    models.Index(
                        fields=["group", "-created_at"],
                        name="withdrawal_group_time_idx",
                    ),
                ],
            },
        ),
    ]
