# Generated by Django 5.2.17 on 2026-09-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0057_withdrawalauditevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalauditevent",
            name="withdrawn_by_candidate",
            field=models.BooleanField(default=False),
        ),
    ]
